default_platform(:ios)

platform :ios do
  lane :release do
    increment_version_number(bump_type: "minor")
    capture_screenshots
    build_app(scheme: "UBB", include_bitcode: true)
    upload_to_app_store
  end
  
  lane :beta do
    increment_version_number(bump_type: "minor")
    capture_screenshots
    build_app(scheme: "UBB", include_bitcode: true)
    upload_to_testflight
  end
  
  lane :upload_symbols do
    download_dsyms
    sentry_upload_dsym
  end
end

